### ISSUE TITLE
Update OIC to oic-0.11.0.1

### ISSUE THREAD

**Issue by andrewkrug** [zamzterz/Flask-pyoidc#21]
We had a fairly important bugfix drop in oic and it would be great to get flask-pyoidc in using that.  

However, there appears to be a breaking change when I test:

```
Traceback (most recent call last):
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/flask_pyoidc/flask_pyoidc.py", line 228, in _handle_authentication_response
    authn_method=self.client.registration_response.get('token_endpoint_auth_method', 'client_secret_basic')
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/oic/oic/__init__.py", line 653, in do_access_token_request
    authn_method, **kwargs)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 761, in do_access_token_request
    http_args=http_args, **kwargs)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 684, in request_and_return
    **kwargs)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 638, in parse_request_response
    state, **kwargs)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 565, in parse_response
    verf = resp.verify(**kwargs)
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/oic/oic/message.py", line 303, in verify
    if not idt.verify(**kwargs):
  File "/Users/akrug/workspace/sso-dashboard/env/lib/python2.7/site-packages/oic/oic/message.py", line 684, in verify
    '{} != {}'.format(kwargs['iss'], self['iss']))
IssuerMismatch: auth.mozilla.auth0.com != https://auth.mozilla.auth0.com/
```

**Comment by andrewkrug** [comment]
This actually turned out to be an issue with the way I registered my provider.
