### ISSUE TITLE
Logout with Blueprints

### ISSUE THREAD

**Issue by fknebel1** [zamzterz/Flask-pyoidc#48]
I have a Flask Application Factory and I use blueprints to structure my Application. The login works fine, but I have problems implementing the logout. 

`@main.route('/logout_user')
@auth.oidc_logout
def logout_function():
    return "You've been successfully logged out!"`

When i call /logout_user i get this error: 
werkzeug.routing.BuildError: Could not build url for endpoint 'logout_function'. Did you mean 'main.logout_function' instead?

Theoretically I should pass 'main.logout_function' somehow to 'oidc_logout' so it knows which function it should use. But I don't have a clue on how to do that. Any idea on how to solve this problem is greatly appreciated.

Thanks

**Comment by zamzterz** [comment]
Thanks for your report! :)
That's a use case I hadn't considered, but I've made a fix for it in #50. It allows you to specify the full URL to the logout endpoint.

Would you be able to test it out and see if it works for you? I've updated the description of the config in the logout section of the README in that PR?

**Comment by fknebel1** [comment]
I will try to test it this week. Thanks for the quick reply and even faster fix. :D

**Comment by fknebel1** [comment]
I tried, but it did not work for me. I configured the static the Information like this`
ClientMetadata(CLIENT,
                                                                       '<mysecret>',
                                                                       post_logout_redirect_uris=
                                                                       ['http://localhost:5000/sample'])
`

But when i call the logout function I get more or less the same Error:


```
Traceback (most recent call last):
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask_pyoidc\flask_pyoidc.py", line 214, in wrapper
    redirect_to_provider = self._logout()
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask_pyoidc\flask_pyoidc.py", line 196, in _logout
    post_logout_redirect_uri=self._get_post_logout_redirect_uri(),
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask_pyoidc\flask_pyoidc.py", line 70, in _get_post_logout_redirect_uri
    return url_for(self._logout_view.__name__, _external=True)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\workspace\backend\e2e\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "C:\workspace\backend\e2e\venv\lib\site-packages\werkzeug\routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'logout_function'. Did you mean 'main.logout_function' instead?
```

**Comment by zamzterz** [comment]
For me it the following minimal working example works correctly:
```python
from flask import Blueprint
from flask import Flask

from flask_pyoidc.flask_pyoidc import OIDCAuthentication
from flask_pyoidc.provider_configuration import ClientMetadata
from flask_pyoidc.provider_configuration import ProviderConfiguration
from flask_pyoidc.provider_configuration import ProviderMetadata

main = Blueprint('main', __name__)
provider_metadata = ProviderMetadata(issuer='...',
                                     authorization_endpoint='...',
                                     jwks_uri='...',
                                     end_session_endpoint='...')
client_metadata = ClientMetadata('<client_id>',
                                 '<client_secret>',
                                 post_logout_redirect_uris=['http://localhost:5000/logout'])
config = ProviderConfiguration(provider_metadata=provider_metadata,
                               client_metadata=client_metadata)
auth = OIDCAuthentication({'login-service': config})


@main.route('/')
@auth.oidc_auth('login-service')
def index():
    return "You're logged in!"


@main.route('/logout')
@auth.oidc_logout
def logout_function():
    return "You've been successfully logged out!"


app = Flask(__name__)
# See http://flask.pocoo.org/docs/0.12/config/
app.config.update({'SERVER_NAME': 'localhost:5000',
                   'SECRET_KEY': 'dev_key',  # make sure to change this!!
                   'PREFERRED_URL_SCHEME': 'http',
                   'DEBUG': True})
app.register_blueprint(main)

if __name__ == '__main__':
    auth.init_app(app)
    app.run()
```

With the config (especially note the `end_session_endpoint` in the `ProviderMetadata`  and `post_logout_redirect_uris` in the `ClientMetadata`) I can't reproduce your error.

Could you test the above (modifying the configuration to your environment)?

**Comment by fknebel1** [comment]
I cant seem to finish the login when i define the 'end_session_endpoint', I get this response:
```
Traceback (most recent call last):
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\workspace\Flask-pyoidc\venv\lib\site-packages\flask-1.1.1-py3.7.egg\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\workspace\Flask-pyoidc\src\flask_pyoidc\flask_pyoidc.py", line 147, in _handle_authentication_response
    flask.session.pop('nonce'))
  File "C:\workspace\Flask-pyoidc\src\flask_pyoidc\auth_response_handler.py", line 66, in process_auth_response
    if 'error' in token_resp:
TypeError: argument of type 'NoneType' is not iterable
```
When I leave it out, i can finish the login, but the logout is still not working.

**Comment by zamzterz** [comment]
Many thanks for testing again! I'm not entirely sure why it doesn't work if you set the `end_session_endpoint` (was that the only difference between your tests?). Because that error looks like a bug I just fixed when the `token_endpoint` is not configured (#54), leading to the missing token response not being handled gracefully. I've updated #50 to contain that fix as well. Would you mind testing again to see if you can get it to work now? 🙂
