### ISSUE TITLE
Error responses using undefined _redirect_uri_endpoint attribute

### ISSUE THREAD

**Issue by lucasdurand** [zamzterz/Flask-pyoidc#94]
In some cases (e.g. when the auth state goes stale after much time) we rightfully receive an error that should be passed on to the client

```python
Exception on /redirect_uri [POST]

Traceback (most recent call last):

  File "../flask_pyoidc/flask_pyoidc.py", line 156, in _handle_authentication_response

    flask.session.pop('nonce'))

  File "../lib/python3.7/site-packages/flask_pyoidc/auth_response_handler.py", line 60, in process_auth_response

    raise AuthResponseErrorResponseError(auth_response.to_dict())

flask_pyoidc.auth_response_handler.AuthResponseErrorResponseError: {'error': 'login_required', 'state': 'm92iSPHP7qMBXSkQ'}

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "../lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

  File "../lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "../lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

  File "../lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

  File "../lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "../lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise

    raise value

  File "../lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

  File "../lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "../lib/python3.7/site-packages/flask_pyoidc/flask_pyoidc.py", line 158, in _handle_authentication_response

    return self._handle_error_response(e.error_response, is_processing_fragment_encoded_response)

  File "../lib/python3.7/site-packages/flask_pyoidc/flask_pyoidc.py", line 186, in _handle_error_response

    return '/' + self._redirect_uri_endpoint + '?error=1'

AttributeError: 'OIDCAuthentication' object has no attribute '_redirect_uri_endpoint'
```

Unfortunately it looks like the error handler tries to return a nonexistant attribute (holdover from old code?) for the redirect uri endpoint. I'm guessing this should be 
`self._redirect_uri_config.endpoint` instead.

**Comment by zamzterz** [comment]
Thanks for the detailed report and correct assessment of the fix (it was indeed leftover old code) 🙇 .
Fixed in #96
